- pkg/operator/keys.go
- pkg/operator/keys/export.go
- pkg/operator/keys/export_test.go
- pkg/operator/keys/flags.go
Fixes #19  .
Implement export key command so that users can export the private keys
- added export command for bls and esdsa keys
> add export key command

- go.mod
- go.sum
- pkg/operator/register.go
- pkg/operator/status.go
- pkg/operator/update.go
Fixes # .
Upgrade to new eigensdk
- Upgrade to new eigensdk
> upgrade to eigensdk v0.0.9

- README.md
Fixes # .
One place for docs - no redundancy
> update eigenlayer cli docs to refer docs website

- cmd/eigenlayer/main.go
> release 0.5.2

- cmd/eigenlayer/main.go
> update version v0.6.2

- README.md
Fixes # .
Add release instructions
> add release instructions

- pkg/operator/keys/create.go
- pkg/operator/keys/import.go
Fixes # .
Differentiate between empty password from pipe vs actual empty password.
> allow empty password via pipe

- pkg/utils/utils.go
Fixes # .
Add Delegation Manager for Mainnet
> add DM for mainnet

- pkg/utils/utils.go
> chore: update for holesky

- pkg/operator/register.go
> add line end

- pkg/operator/keys/create.go
Fixes # .
Pad ecdsa with 00 since it gets trimmed
> fix: pad ecdsa key with 00

- cmd/eigenlayer/main.go
- go.mod
- go.sum
> update to have regex

- cmd/eigenlayer/main.go
> bump version

- pkg/operator/config/create.go
- pkg/operator/config/operator-config-example.yaml
- pkg/operator/register_test.go
- pkg/utils/constants.go
- pkg/utils/utils.go
Fixes # .
Deprecate Goerli support!
> deprecate goerli

- pkg/operator/config/create.go
- pkg/operator/register.go
- pkg/operator/status.go
- pkg/operator/update.go
Fixes # .
Add some chain validation
> add more validation

- pkg/types/operator_config.go
> fix marshall yaml bug

- pkg/operator/config/create.go
- pkg/utils/mocks/prompter.go
- pkg/utils/prompter.go
Fixes # .
- Added fireblocks option during config creation
> fireblocks in create config

- LICENSE
Fixes # .
- Additional grant use license update
- Update change date
> chore: additional grant use license update

- pkg/operator/config/create.go
- pkg/operator/register.go
- pkg/operator/register_test.go
- pkg/types/operator_config.go
> chore: cleanup config type

- pkg/operator/register.go
- pkg/operator/status.go
- pkg/operator/update.go
- pkg/telemetry/telemetry.go
- pkg/utils/utils.go
Fixes # .
- Add network to relevant cmd
> add network to relevant cmd

- pkg/operator/register.go
- pkg/operator/update.go
Fixes # .
Add a delay message to registration and update calls
> add delay message

- README.md
Fixes # .
- Update readme to remove version changing while release
> chore: update release readme

- .github/workflows/codeql-analysis.yml
> change name of file

- pkg/operator/config/create.go
- pkg/operator/helper.go
- pkg/operator/register.go
- pkg/operator/setclaimer.go
- pkg/types/fireblocks_config.go
- pkg/types/operator_config.go
- pkg/types/signer_config.go
- pkg/types/web3_config.go
Fixes # .
- Refactor Signer to it's own struct for re-use.
> refactor signer to it's own config

- pkg/common/errors.go
- pkg/common/helper.go
- pkg/common/helper_test.go
- pkg/operator/errors.go
- pkg/operator/register.go
- pkg/operator/setclaimer.go
- pkg/operator/status.go
- pkg/operator/update.go
Fixes # .
- Refactor common for other packages to use
> chore: refactor to common

- pkg/common/helper.go
- pkg/operator/register.go
- pkg/operator/setclaimer.go
- pkg/operator/status.go
- pkg/operator/update.go
- pkg/types/signer_config.go
Fixes # .
- Add back private key signer so it's easy to test
> add back private key signer

- .github/workflows/integration-test.yml
- pkg/operator.go
- pkg/operator/update_metadata_uri.go
Fixes # .
- Since we update SDK, we have added a new command `update-metadata-uri`
> add update metadata uri command

- pkg/rewards/claim.go
Fixes # .
- Claim command not supported in mainnet
> claim command only in testnet

- README.md
> docs: update readme to include latest features and other support

- .github/workflows/integration-test.yml
- pkg/operator/config/create.go
- pkg/utils/constants.go
- pkg/utils/utils.go
- tests/keystore/operator-ci.yaml
- tests/web3signer/operator-ci.yaml
Fixes # .
- Add set claimer tests
- update existing test to use eigensdk anvil contracts
> tests: add set claimer integration tests

- .github/workflows/integration-test.yml
Fixes # .
- fix pass in web3 signer tests
> tests: remove pass from CI

- pkg/common/fileio.go
- pkg/rewards/claim.go
Fixes # .
- Support `--output` flag to output the claim details
> feat: support output to file for claims

- go.mod
- go.sum
- pkg/common/fileio.go
- pkg/rewards/show.go
- pkg/rewards/types.go
Fixes # .
- Support output flag option for Rewards
> feat: output rewards to csv

- .github/workflows/release.yml
Fixes # .
- fix release pipeline with new env var
> fix: release pipeline with new env vars

- pkg/common/helper.go
- pkg/operator/register.go
- pkg/operator/status.go
- pkg/operator/update.go
- pkg/operator/update_metadata_uri.go
- pkg/rewards/claim.go
- pkg/rewards/setclaimer.go
- pkg/rewards/show.go
Fixes # .
- Refactor
- logging changes
> chore: update logging and refactor

- go.mod
- go.sum
- pkg/operator/register.go
- pkg/operator/status.go
- pkg/operator/update.go
- pkg/operator/update_metadata_uri.go
Fixes # .
- replace deprecated methods and update eigensdk
> chore: remove deprecated methods

- internal/versionupdate/check_version_update.go
- pkg/internal/common/flags/common.go
- pkg/rewards/claim.go
- pkg/rewards/setclaimer.go
- pkg/rewards/show.go
Fixes # .
- Refactor to move signer flags in a function
- Sort flags
> chore: refactor signer flags

- pkg/eigenpod/status.go
- pkg/internal/testutils/fuzz.go
- pkg/keys.go
- pkg/rewards/claim.go
- pkg/rewards/claim_test.go
- pkg/rewards/setclaimer.go
- pkg/utils/utils_test.go
Fixes # .
- Clean up
- Add some tests
> chore: clean up and tests

- go.mod
- go.sum
Fixes # .
- update rewards libs
> chore: update reward libs

- pkg/rewards/claim.go
> fix: rewards command message

- pkg/rewards/claim.go
- pkg/rewards/setclaimer.go
- pkg/rewards/show.go
- pkg/utils/utils.go
> feat: support rewards for mainnet

- go.mod
- go.sum
> chore: update rewards repo version

- pkg/rewards/claim.go
Fixes # .
- Fix mainnet claim url
> fix: fix the mainnet url

- go.mod
- go.sum
- pkg/operator/register.go
- pkg/operator/update.go
- pkg/operator/update_metadata_uri.go
- pkg/rewards/claim.go
- pkg/rewards/claim_test.go
- pkg/rewards/setclaimer.go
Fixes # .
- Get latest active root via contract call instead of S3
> feat: latest active root via contract call

- pkg/internal/common/eth.go
- pkg/rewards/claim.go
- pkg/rewards/claim_test.go
- pkg/rewards/setclaimer.go
Fixes # .
- Add transaction fee details to rewards tx
> feat: add tx fee details in non broadcast mode

- .github/workflows/release.yml
- .goreleaser.yml
Fixes # .
- Update go releaser
- Remove unused dependency download
> chore: update and clean go releaser

- .goreleaser.yml
Fixes # .
- Add goreleaser build version
> chore: add tag to go releaser

- pkg/internal/common/contracts.go
- pkg/internal/common/helper.go
- pkg/operator/register.go
- pkg/operator/update.go
- pkg/operator/update_metadata_uri.go
- pkg/rewards/claim.go
- pkg/rewards/setclaimer.go
Fixes # .
- Move the EL writer initialization to common
> chore: move el writer initialization to common

- .github/workflows/release.yml
- .goreleaser.yml
- pkg/telemetry/telemetry.go
> chore: fix build

- .github/workflows/golangci-lint.yml
- .github/workflows/release.yml
> chore: update deps

- pkg/internal/common/constants.go
- pkg/internal/common/eth.go
- pkg/internal/common/helper.go
- pkg/operator/config/create.go
- pkg/rewards/claim.go
- pkg/rewards/setclaimer.go
- pkg/utils/utils.go
Fixes # .
- Some refactor to move code to internal.
> chore: refactor and move to internal

- go.mod
- go.sum
- pkg/rewards/claim.go
Fixes # .
- Add claim check after generation
> feat: add claim check after generation

- README.md
> chore: add detailed rewards cmd to readme

- internal/versionupdate/check_version_update.go
Fixes # .
- Fixes a case where API returns non 200 response and version update panics
- this should be silently passed.
> bug: silent pass when API not 200

- pkg/rewards/README.md
Fixes # .
- Update rewards readme
> docs: update readme with latest updates

- pkg/rewards/README.md
- pkg/rewards/claim.go
- pkg/rewards/claim_test.go
- pkg/rewards/flags.go
- pkg/rewards/show.go
- pkg/rewards/types.go
Fixes # .
- This allows us to see rewards based on latest non claimable root too.
> feat: extend show to latest non claimable root

- pkg/internal/erc20/erc20.go
- pkg/rewards/show_test.go
Fixes # .
- Add tests where calculation can get buggy
- Fix some other bugs
> tests: add tests for some calculations

- pkg/keys/import.go
- pkg/keys/import_test.go
Fixes #242  .
- Add a way to have keys imported via a prompt to user
> feat: add optional prompt option for importing keys

- pkg/operator/allocations/update_test.go
- pkg/user/admin/accept.go
- pkg/user/admin/add_pending.go
- pkg/user/admin/remove.go
- pkg/user/admin/remove_pending.go
- pkg/user/appointee/batch_set.go
- pkg/user/appointee/can_call.go
- pkg/user/appointee/can_call_test.go
- pkg/user/appointee/remove.go
- pkg/user/appointee/set.go
- pkg/user/appointee/types.go
> fix: tests and fmt

- pkg/operator/config/create.go
- pkg/user/admin/types.go
- pkg/user/appointee/remove_test.go
- pkg/user/appointee/set_test.go
- tests/keystore/operator-ci.yaml
- tests/web3signer/operator-ci.yaml
- allocation delay config
- tests
> fix: allocation delay config and update tests

- go.mod
- go.sum
- pkg/user/appointee/remove.go
- pkg/user/appointee/remove_test.go
- pkg/user/appointee/set.go
- pkg/user/appointee/set_test.go
Updating appointe set & remove to support output parameters.
- Output support for user appointee write commands
- Unit test updates
> Updating appointee set & remove to support output parameters

- pkg/operator/allocations/show.go
- pkg/operator/allocations/types.go
Fixes # .
- Add CSV output for showing allocations
> feat: support csv out for show command

- pkg/user/admin/accept.go
- pkg/user/admin/add_pending.go
- pkg/user/admin/is_admin.go
- pkg/user/admin/is_pending.go
- pkg/user/admin/remove.go
- pkg/user/admin/remove_pending.go
- pkg/user/appointee/can_call.go
- pkg/user/appointee/list.go
- pkg/user/appointee/list_permissions.go
- pkg/user/appointee/remove.go
- pkg/user/appointee/set.go
Fixing name casing for PermissionController.
- Fixing name casing.
> Fixing name casing for PermissionController.

- .github/workflows/integration-test.yml
- go.mod
- go.sum
- pkg/operator/get_operator_split.go
- pkg/operator/set_operator_split.go
- pkg/rewards/claim.go
* Updates eigensdk to commit in master branch to avoid accidentally deleting dependent commit
* Removes gate on rewards v2 functions previously gated to testnet
> feat: Mainnet release for rewards v2 CLI

- README.md
Updated to new links to Operator docs.
> chore: Updated README with updated doc links

- .github/workflows/build.yml
- .github/workflows/check-fmt.yml
- .github/workflows/golangci-lint.yml
- .github/workflows/integration-test.yml
- .github/workflows/release.yml
- .github/workflows/tests.yml
> fixing hashes
