Layr-Labs/eigenlayer-cli

pkg/operator/keys/create.go, pkg/operator/keys/create_test.go, pkg/operator/keys/import_test.go
Fixes # .
When user try to create a new key by using `eigenlayer`, the user should enter a password to encrypt keystore. But there is no password confirmation steps even thought the password is very important.
Add a new simple step to confirm password.
=> confirm password when a new key is creating

pkg/operator/keys/create.go
Fixes #29
Update to the issue #29 with adding bold text and emojis as discussed.
Added syntax for changing text color and emoji unicode
Will look into fixing the TODO in the code with using `less` with `vi`
=> Bold green text and emojis on the key creation to save private key hex

pkg/operator/keys/create.go
Fixes the TODO in the code for displaying sensitive information in: 
https://github.com/Layr-Labs/eigenlayer-cli/blob/754ca6832861c6b1d9df3d507c04365efea70401/pkg/operator/keys/create.go#L137-L143
and
https://github.com/Layr-Labs/eigenlayer-cli/blob/754ca6832861c6b1d9df3d507c04365efea70401/pkg/operator/keys/create.go#L188-L196
- Increased Security: By removing direct terminal outputs of private keys, we significantly reduce the risk of sensitive data exposure. This change is crucial for users who manage keys in shared or insecure environments.
- Improved Usability: The introduction of a formatted display for key information, including private and public keys, addresses, and file locations, enhances clarity and user experience. This structured presentation makes it easier for users to …
=> Displaying sensitive information during key creation with using `less` so is not saved in terminal history

pkg/operator/config/create.go, pkg/operator/config/create_test.go, pkg/operator/config/flags.go
The current `eigenlayer operator config create` command is interactive only, and using tools like `expect` does not work because the prompt library the CLI is using sends a weird `^[[61;169R` cursor code that doesn't allow a proper expect/send pipeline. 
I'm creating Ansible playbooks to automate the registration process of an AVS Operator, among other operations related to AVS Operator duties. I can't automate the registration process fully without solving this problem
Adding a `--yes/-y` flag to skip the confirmation prompt allows automating the `eigenlayer operator config create` call, creating the `operator.yaml` and `metadata.json` files just as if you press enter in the current and interactive mode.
This kind of proposed behavior is quite standard in CLI applications.
=> [operator config] Add --yes flag to skip prompt

pkg/operator/register.go
If delegation manager address key is missing in the .env user would be receiving misleading error about Slasher address: 
```
Failed to fetch Slasher address: no contract code at given address
```
Added check for non empty ELDelegationManagerAddress in the config reverting with relevant error message
=> feat: revert if delegation manager is missing

.github/workflows/integration-test.yml, pkg/operator/config/create.go, pkg/operator/update.go, pkg/utils/utils.go
Fixes # .
- Support PIPE for update operator details
- remove goerli from create command
- add AVS directory contract for mainnet
=> add piping for update

pkg/operator/config/operator-config-example.yaml
Our example operator config referenced https://docs.eigenlayer.xyz/eigenlayer/operator-guides/operator-installation#operator-registration is broken
If operator uses that template and does not update the chain id, they will have bunch of esoteric opt-in failures.
Reduced cognitive load on new operator debugging opt-in
Update chain id to holesky
=> Replace goerli chain id with holesky in example operator config

pkg/operator/config/create.go
Fixes # .
Add a content policy warning
=> add content policy warning

pkg/operator/register.go, pkg/operator/update.go
Fixes #98  .
Go by default doesn't support tilde so converting from tilde to full path
=> support ~ in path

.github/PULL_REQUEST_TEMPLATE.md, pkg/operator/register.go, pkg/operator/status.go, pkg/types/operator_config.go
Fixes # .
It's been 2 months that we added config migration. almost everyone on holesky and mainnet would use new config so removing old config and migration logic
=> remove old config

README.md
Fixes FAQ "Page Not Found" error.
The original link to the FAQ page was pointing to a non-existent page (https://docs.eigenlayer.xyz/operator-guides/faq), resulting in a "Page Not Found" error. Replaced it with the correct FAQ link (https://docs.eigenlayer.xyz/operator-guides/operator-faq).
=> Correct FAQ hyperlink

pkg/operator/register.go, pkg/operator/update.go, pkg/types/operator_config.go
Fixes # .
- Add support for fireblocks wallet signer
- The yaml file just takes the secret value directly. Will support AWS KMS in subsequent PR.
=> add support for fireblocks wallet

pkg/operator/register.go
Very minor update, and arguably opinionated. Adds spacing between the operator address and subsequent error message. Also explicitly uses the string returned by `err.Error()`, and removes a redundant `with error`. Happy to add that back in though!
Before (assuming address == `0xabcd`)
```
validating operator config: 0xabcdinvalid yaml file: with error invalid image extension. only .pngis supported
```
After
```
validating operator config: 0xabcd ... invalid yaml file: invalid image extension. only .pngis supported
```
(I'm aware the spacing of `.pngis supported` was addressed here: https://github.com/andrewkmin/eigensdk-go/commit/16ddf1b87f57f6ca5996678bdc8d50646286f2f6)
Readability
=> clarify error message

.github/workflows/build.yml, .github/workflows/golangci-lint.yml, .github/workflows/release.yml, .github/workflows/tests.yml
Node16 is deprecated and Actions using it will stop working 3rd of June
https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
=> upgrade checkout action to version using node20

.github/workflows/integration-test.yml
Fixes # .
- Add Web3 signer tests
=> tests: add Integration test for web3 signer

pkg/rewards/claim.go
Fixes # .
- Fix bug when no broadcast and no signer details provided
=> fix: do not fail if no signer is provided when there's no broadcast flag

go.mod, go.sum, pkg/operator/config/create.go, pkg/operator/config/operator-config-example.yaml, pkg/operator/status.go, tests/keystore/operator-ci.yaml, tests/web3signer/operator-ci.yaml
Fixes # .
- Remove earning receiver address
=> chore: remove earning receiver address

pkg/rewards/README.md, pkg/rewards/claim.go, pkg/rewards/claim_test.go, pkg/rewards/flags.go
Fixes # .
- Add support for an user to claim rewards at the latest active root instead of latest available root since latest available root can be inactive
=> feat: claim rewards from last active root

pkg/rewards/show.go
Fixes # .
- fix mainnet endpoint
- bug fix env
=> fix: update claim URL and refactor

Makefile, internal/versionupdate/check_version_update.go, pkg/internal/common/helper.go, pkg/keys/import.go, pkg/keys/import_test.go, pkg/operator/keys/import.go, pkg/operator/keys/import_test.go
Fixes # .
- Trim `0x` from private key so any format is acceptable.
- Some formatting related changes
=> chore: trim `0x` from private key

pkg/internal/common/helper.go, pkg/rewards/README.md, pkg/rewards/claim.go, pkg/rewards/flags.go, pkg/rewards/setclaimer.go
Fixes # .
- There is a bug where we can't set claimer address in non broadcast mode when earner has set a new claimer address. This PR adds that and fixes it. 
- In the broadcast mode, it depends on the signer so that path was working
- Some debug logging improvements
=> fix: add claimer address flag when claimer is not earner for claim method

pkg/internal/common/eth.go, pkg/rewards/claim.go
Fixes # .
If the claimer is smart contract, we disable the estimation of `gasLimit` as the contract might not have it's own balance since it can be called by EOA.  
So we hardcode gas limit in  non-broadcast mode so that we can generate unsigned transaction.
=> fix: hardcode gas limit for smart contract claimer

pkg/rewards/claim.go, pkg/rewards/claim_test.go, pkg/rewards/setclaimer.go, pkg/rewards/show.go, pkg/rewards/types.go
=> chore: clean up and tests 1 of n

.github/workflows/release.yml, .goreleaser.yml, pkg/telemetry/telemetry.go
This reverts commit 3431a4d.Fixes # .
=> revert: some build changes

pkg/keys/create.go, pkg/keys/error.go, pkg/keys/import.go, pkg/keys/import_test.go
Fixes # .
- support bip39 imports
=> feat: support bip39 mnemonic for importing keys

pkg/rewards/README.md, pkg/rewards/flags.go, pkg/rewards/show.go
Fixes # .
- Fix readme
- Add show to readme
=> chore: fix readme for rewards show

.github/workflows/release.yml, .goreleaser.yml, go.mod, go.sum, pkg/rewards/README.md, pkg/rewards/show.go, pkg/rewards/types.go
Fixes # .
- Remove BE API dependency from `rewards show`
- Only dependency now is RPC
- remove `number-of-days` params
=> feat: remove backend API deps for show cmd

pkg/rewards/claim.go, pkg/rewards/claim_test.go, pkg/rewards/flags.go
https://github.com/Layr-Labs/eigenlayer-cli/issues/220
Prior to this change, users trying to claim rewards needed to know the token addresses they intend to claim rewards for. When no rewards are present, they receive errors and logs indicating the issue. They must iteratively remove token addresses from their input until they've reduced the set to addresses with claimable rewards. Also, they are _required_ to know the token address of the rewards they want to claim. Users need a mechanism in the CLI to address these pain points.
This change brings two behavioral changes to the API. 
1. When no `tokenAddresses` is provided, or it's empty, the CLI uses the public rewards distribution to claim all available rewards.
2. When `tokenAddresses` are provided, the CLI uses the public rewards …
=> ELO-335 -- lowering claim tokenAddresses to optional; using distribution to only query claimable tokens.

pkg/internal/erc20/erc20.go, pkg/rewards/show.go, pkg/rewards/types.go
Fixes # .
- Adds token name to show rewards output
=> feat: add token name to show cmd

pkg/operator/get_delegation_approval.go
Fixes # .
- When no signer is provided, the command fails. But we want to generate salt for the approver to sign by themselves. This fixes it.
=> fix: bug in delegation approval when no signer provided

go.mod, go.sum, pkg/operator/get_delegation_approval.go, pkg/operator/register.go, pkg/operator/status.go, pkg/rewards/claim.go, pkg/rewards/claim_test.go, pkg/rewards/show.go, pkg/rewards/show_test.go
Update eigenlayer-cli to work with the latest changes introduced in the eigensdk here: https://github.com/Layr-Labs/eigensdk-go/commit/565bb4438918c85469763e6af07621b123e94a19
=> fix: updates to support latest eigensdk

pkg/rewards/setclaimer.go
This fixes panic using SetClaimer when unhandled GetTxFeeDetails returns nil transaction instead of returning error.
Example of before fix:
```panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x1010a6d40]
goroutine 1 [running]:
github.com/ethereum/go-ethereum/core/types.(*Transaction).GasTipCap(0x0)
/Users/aivaras/go/pkg/mod/github.com/ethereum/go-ethereum@v1.14.5/core/types/transaction.go:295 +0x30
github.com/Layr-Labs/eigenlayer-cli/pkg/internal/common.GetTxFeeDetails(0x0)
/Users/aivaras/projects/eigenlayer-cli/pkg/internal/common/eth.go:37 +0x24
...	
```
Fix would return more informative error like:
```failed to create unsigned tx: no contract code at given address```
=> Fix panic: runtime error on SetClaimer

pkg/rewards/claim.go, pkg/rewards/claim_test.go, pkg/rewards/show.go
Fixes # .
The current logic generates proof for tokens where all the amount has already been claimed. The current smart contract logic https://github.com/Layr-Labs/eigenlayer-contracts/blob/ac57bc1b28c83d9d7143c0da19167c148c3596a3/src/contracts/core/RewardsCoordinator.sol#L575-L578 expects that the claim proof should only have token where there's something eligible for claiming. the S3 root provides all the tokens no matter if it's claimable or not as it provides cummulative state. 
We added a filter which would filter out tokens where s3 root amount is equal to the cummulative claimed from onchain state  for a particular token
=> fix: already claimed tokens should not be in claim proof

go.mod, go.sum, pkg/internal/common/flags/general.go, pkg/rewards/claim.go, pkg/rewards/types.go, samples/batch-claims.yaml
Adds batch claiming support for rewards v2:
`./eigenlayer rewards claim --earner-address 0x025246421e7247a729bbcff652c5cc1815ac6373 --eth-rpc-url http://rpc-url
--network holesky --batch-claim-file samples/batch-claim.yaml`
Example batch claim file provided in samples/batch-claim.yaml
Eigensdk has been updated to include process claims.
=> feat: Rewards v2 batch claiming support

go.mod, go.sum, pkg/user/appointee/appointee.go, pkg/user/appointee/can_call.go, pkg/user/appointee/list.go, pkg/user/appointee/list_permissions.go, pkg/user/appointee/list_permissions_test.go, pkg/user/appointee/list_test.go, pkg/user/appointee/types.go
Implementing `list` and `list_permissions` Commands.
- Minor refactors for `can-call` command.
- Added `user list` command.
- Added `user list-permissions` command.
- Added unit tests for both commands.
=> Implementing `list` and `list_permissions` Commands.

go.mod, go.sum, pkg/user/admin/accept.go, pkg/user/admin/accept_test.go, pkg/user/admin/add_pending.go, pkg/user/admin/add_pending_test.go, pkg/user/admin/admin.go, pkg/user/admin/flags.go, pkg/user/admin/is_admin.go, pkg/user/admin/is_pending.go, pkg/user/admin/list.go, pkg/user/admin/list_pending.go, pkg/user/admin/remove.go, pkg/user/admin/remove_pending.go, pkg/user/admin/remove_pending_test.go, pkg/user/admin/remove_test.go, pkg/user/admin/types.go, pkg/user/appointee/list.go, pkg/user/appointee/remove.go, pkg/user/appointee/set.go, pkg/users.go
Adding implementation and tests for admin write commands.
- Implementation of RemovePendingAdmin
- Implementation of AddPendingAdmin
- Implementation of AcceptAdmin
- implementation of RemoveAdmin
- Tests for all three commands
=> Adding implementation and tests for admin write commands.

pkg/user/admin/accept.go, pkg/user/admin/add_pending.go, pkg/user/admin/is_admin.go, pkg/user/admin/is_pending.go, pkg/user/admin/list.go, pkg/user/admin/list_pending.go, pkg/user/admin/remove.go, pkg/user/admin/remove_pending.go, pkg/user/appointee/batch_set.go, pkg/user/appointee/list.go, pkg/user/appointee/list_permissions.go, pkg/user/appointee/remove.go, pkg/user/appointee/set.go
Cleaning up user command flags.
- Removing output type/file flags where not needed.
- sorting flags after fully collected.
=> Cleaning up user command flags.

go.mod, go.sum, pkg/user/admin/flags.go, pkg/user/admin/is_admin.go, pkg/user/admin/is_admin_test.go, pkg/user/appointee/appointee.go, pkg/user/appointee/can_call.go, pkg/user/appointee/can_call_test.go, pkg/user/appointee/flags.go, pkg/user/appointee/list.go, pkg/user/appointee/list_permissions.go, pkg/user/appointee/list_permissions_test.go, pkg/user/appointee/list_test.go, pkg/user/appointee/remove.go, pkg/user/appointee/remove_test.go, pkg/user/appointee/set.go, pkg/user/appointee/set_test.go, pkg/user/appointee/types.go
Refactoring user commands to remove user nomenclature and replacing with appointee.
- replacing user nomenclature with appointee
=> Refactoring user commands to remove user nomenclature and replacing with appointee

.github/workflows/integration-test.yml, pkg/internal/common/helper.go
=> fix: integration test

go.mod, go.sum, pkg/operator.go, pkg/operator/get_operator_pi_split.go, pkg/operator/get_operator_split.go, pkg/operator/set_operator_pi_split.go, pkg/operator/set_operator_split.go
Adds operator split command for rewards v2:
`./eigenlayer operator set-pi-split --operator-address 0x025246421e7247a729bbcff652c5cc1815ac6373 --avs-address 0xfF95c28C1c38bbb26EC7Ad0BAf7b17375Ff6315C --eth-rpc-url http://rpc-url --network holesky --split 1000 --broadcast`
Eigensdk has been updated to include getting / setting methods in https://github.com/Layr-Labs/eigensdk-go/pull/406
=> feat: get/set operator PI split commands

go.mod, go.sum, pkg/internal/common/flags/general.go, pkg/operator.go, pkg/operator/get_operator_pi_split.go, pkg/operator/get_operator_split.go, pkg/operator/set_operator_pi_split.go, pkg/operator/set_operator_split.go, pkg/operator/split/flags.go, pkg/operator/split/types.go, pkg/rewards/claim.go, pkg/rewards/types.go, samples/batch-claims.yaml
Final rewards v2 release branch with commands gated to holesky
=> feat: Rewards v2 release

pkg/internal/common/flags/general.go, pkg/operator/allocations/set_allocation_delay.go, pkg/operator/allocations/show.go, pkg/operator/allocations/types.go, pkg/operator/allocations/update.go
- Add a `caller-address` flag for unsigned tx.
=> fix: add caller address

pkg/user/admin/accept.go, pkg/user/admin/flags.go, pkg/user/admin/types.go, pkg/user/appointee/flags.go, pkg/user/appointee/remove.go, pkg/user/appointee/set.go, pkg/user/appointee/types.go
Adding caller-address to support arbitrary CLI signing address.
Signers of this command can be arbitrary. The `caller-address` adds support for this use.
=> Adding caller-address to support arbitrary CLI signing address.

pkg/user/admin/accept.go, pkg/user/admin/add_pending.go, pkg/user/admin/admin.go, pkg/user/admin/is_admin.go, pkg/user/admin/is_pending.go, pkg/user/admin/list.go, pkg/user/admin/list_pending.go, pkg/user/admin/remove.go, pkg/user/admin/remove_pending.go, pkg/user/appointee/appointee.go, pkg/user/appointee/can_call.go, pkg/user/appointee/list.go, pkg/user/appointee/list_permissions.go, pkg/user/appointee/remove.go, pkg/user/appointee/set.go
Fixing usage strings for UAM commands.
=> Fixing usage strings for UAM commands.

.github/workflows/integration-test.yml, go.mod, go.sum, pkg/operator/allocations/show.go, pkg/operator/allocations/update.go, pkg/operator/allocations/update_test.go
- get slashable stake from contract call
- fix new magnitudes share calculation.
=> feat: get slashable stake from contract call

pkg/user/admin/accept.go, pkg/user/admin/add_pending.go, pkg/user/admin/flags.go, pkg/user/admin/remove.go, pkg/user/admin/remove_pending.go, pkg/user/admin/types.go, pkg/user/appointee/remove.go
Adding caller-address to user admin commands to specify arbitrary caller with appointed permissions
Fixes # .
- Adding caller-address parameter for write commands.
=> Adding caller-address to user admin commands to specify arbitrary caller with appointed permissions

pkg/operator/allocations/update_test.go
Changes the test assert so that it matches elements of array instead of the array as elements can be in different positions.
=> fix: flakey test

pkg/operator/deregister_operator_sets.go, pkg/operator/register_operator_sets.go, pkg/operator/types.go
Fixes # .
- Add `caller-address` for operator set registration and deregistration
=> fix: add caller address to opset reg/dereg

pkg/user/admin/accept.go, pkg/user/admin/accept_test.go, pkg/user/admin/add_pending.go, pkg/user/admin/add_pending_test.go, pkg/user/admin/remove.go, pkg/user/admin/remove_pending.go, pkg/user/admin/remove_pending_test.go, pkg/user/admin/remove_test.go, pkg/user/admin/types.go
Adding output support to file or terminal without broadcast for user admin commands.
- Output support for user admin write commands
- Broadcast conditional support for user admin write commands
- Unit test updates
=> Adding output support to file or terminal without broadcast for user admin commands.

go.sum, pkg/operator/allocations/show.go, pkg/operator/register_operator_sets.go
Fixes # .
- Fix a case where operator is deregistered and the contract API doesn't return the slashable shares as the operator is deregistered. But protocol still has magnitude allocated (which is no unused) for that case. So in order to show that we make a map of deregistered and show that. We change the order of execution so if don't execute rest of operations if opset is deregistered 
- There's a comment there on how to change order of iteration which will make more sense. We will do it in subsequent PR.
- Fix a bug where we forgot to pass operator address to eigensdk.
=> fix: showing allocations for registered ops

pkg/user/admin/accept.go, pkg/user/admin/add_pending.go, pkg/user/admin/flags.go, pkg/user/admin/remove.go, pkg/user/admin/remove_pending.go, pkg/user/appointee/flags.go, pkg/user/appointee/remove.go, pkg/user/appointee/set.go, pkg/user/flags.go, pkg/user/helper.go
Updating output code path to correctly detect empty string input for caller-address. Because the input was wrapped in an address object, it defaulted to the 0x0.. address which doesn't match the empty string check enforced.
When the caller address is not provided we want to default to the `account-address` provided. 
- properly detects empty `caller-address` and replaces with`account-address`.
=> Updating output code path to correctly detect empty string input for caller-address

pkg/internal/common/helper.go, pkg/types/chain_metadata.go, pkg/user/admin/accept.go, pkg/user/admin/add_pending.go, pkg/user/admin/is_admin.go, pkg/user/admin/is_pending.go, pkg/user/admin/list.go, pkg/user/admin/list_pending.go, pkg/user/admin/remove.go, pkg/user/admin/remove_pending.go, pkg/user/admin/types.go, pkg/user/appointee/can_call.go, pkg/user/appointee/list.go, pkg/user/appointee/list_permissions.go, pkg/user/appointee/remove.go, pkg/user/appointee/set.go, pkg/user/appointee/types.go
Rename of PermissionManager => PermissionController.
- Renaming `PermissionManager` => `PermissionController` to match the contract name.
- Adding anvil `PermissionController` address to helper.
=> Rename permission manager

README.md
The package README didn't have any context around integration testing. This PR adds context on the topic.
Added integration test README section.
Add further context to the eigensdk-go README for anvil setup and usage.
Update this README again with details on how BATS is used and how to execute those tests once they merged to master.
=> Updating the README with integration testing environment details.

pkg/clients/sidecar/client.go
Increase sidecar client timeout since generating rewards data can take a "long" time if not already cached.
=> fix: increase timeout for sidecar client

.github/workflows/release.yml
This is a scheduled Ubuntu 20.04 retirement. Ubuntu 20.04 LTS runner will be removed on 2025-04-15. For more details, see https://github.com/actions/runner-images/issues/11101
The Ubuntu version we're using is retired.
- Fixing failed [release workflow](https://github.com/Layr-Labs/eigenlayer-cli/actions/runs/14502277031/job/40684621631).
=> Updating Ubuntu version for release task.

pkg/operator/allocations/set_allocation_delay.go, pkg/operator/allocations/update.go, pkg/operator/deregister_operator_sets.go, pkg/operator/get_operator_split.go, pkg/operator/register_operator_sets.go, pkg/operator/set_operator_split.go
Fixes # .
This PR makes the `--operator-address` flag a requirement for the `operator set-delay` command. This is needed as UAM supports signing with a private key that is != operator's private key.
Added a check for the empty `--operator-address` string argument.
=> fix: enforce operator address flag

pkg/internal/common/flags/general.go, pkg/internal/common/helper.go, pkg/internal/common/helper_test.go, pkg/keys/import.go, pkg/keys/utils.go, pkg/operator/register_operator_sets.go, pkg/operator/types.go
Fixes # .
- Fixes the `register-operator-sets` command
- Fixes the tx link
This PR fixes the `register-operator-sets` command, by adding flags for the `RegistryCoordinator` address and `BlsPrivateKey` needed for registration to an Operator Set
=> fix: fix operator set registration command
